services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vlm-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - vlm-network
    deploy:
      resources:
        reservations:
          memory: 256M
        limits:
          memory: 1.5G

  worker_1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8001:8001"
    volumes:
      - ./models:/home/appuser/app/models:ro
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKER_PORT=8001
      - API_ACCESSIBLE_HOSTNAME=worker_1
      - API_ACCESSIBLE_PORT=8001
      - MODEL_PATH=/home/appuser/app/models/gemma-3-4b-it-Q4_K_M.gguf
      - MM_PROJECT_PATH=/home/appuser/app/models/ggml-org_gemma-3-4b-it-GGUF_mmproj-model-f16.gguf
      - GPU_LAYERS=35
      - GPU_SPLIT=0.45
      - CUDA_VISIBLE_DEVICES=0
    depends_on:
      - redis
    networks:
      - vlm-network
    deploy:
      resources:
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G

  worker_2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8002:8002"
    volumes:
      - ./models:/home/appuser/app/models:ro
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKER_PORT=8002
      - API_ACCESSIBLE_HOSTNAME=worker_2
      - API_ACCESSIBLE_PORT=8002
      - MODEL_PATH=/home/appuser/app/models/gemma-3-4b-it-Q4_K_M.gguf
      - MM_PROJECT_PATH=/home/appuser/app/models/ggml-org_gemma-3-4b-it-GGUF_mmproj-model-f16.gguf
      - GPU_LAYERS=35
      - GPU_SPLIT=0.45
      - CUDA_VISIBLE_DEVICES=0
    depends_on:
      - redis
    networks:
      - vlm-network
    deploy:
      resources:
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G

networks:
  vlm-network:
    driver: bridge